# Do not truncate path in repos
SPACESHIP_DIR_TRUNC_REPO=true
SPACESHIP_CHAR_SYMBOL="${SPACESHIP_CHAR_SYMBOL="> "}"
SPACESHIP_PROMPT_DEFAULT_PREFIX=""
SPACESHIP_EXEC_TIME_ELAPSED=0
SPACESHIP_EXEC_TIME_PRECISION=2
SPACESHIP_EXEC_TIME_COLOR="yellow"
SPACESHIP_AWS_SHOW=false           # nondefault
SPACESHIP_AZURE_SHOW=false         # nondefault
SPACESHIP_BATTERY_SHOW=false       # nondefault
SPACESHIP_CONDA_SHOW=false         # nondefault
SPACESHIP_DENO_SHOW=false          # nondefault
SPACESHIP_DOCKER_COMPOSE_SHOW=true # true is default
SPACESHIP_DOCKER_SHOW=true         # nondefault
SPACESHIP_DOTNET_SHOW=false        # nondefault
SPACESHIP_ELIXIR_SHOW=false        # nondefault
SPACESHIP_ELM_SHOW=false           # nondefault
SPACESHIP_EMBER_SHOW=false         # nondefault
SPACESHIP_EXIT_CODE_SHOW=true      # nondefault
SPACESHIP_GCLOUD_SHOW=false        # nondefault
SPACESHIP_GNU_SCREEN_SHOW=false    # nondefault
SPACESHIP_PYTHON_PREFIX=""
SPACESHIP_GIT_PREFIX=""
SPACESHIP_DIR_PREFIX="  "
# SPACESHIP_DIR_PREFIX=""
# SPACESHIP_DIR_TRUNC_PREFIX="/"
# SPACESHIP_EXEC_TIME_PREFIX="| took "
SPACESHIP_EXEC_TIME_PREFIX="took "
SPACESHIP_GOLANG_SHOW=false # nondefault
SPACESHIP_HG_SHOW=false     # nondefault
SPACESHIP_HOST_SHOW_FULL=false
SPACESHIP_HOST_SHOW=false
# SPACESHIP_HOST_SHOW="always"
SPACESHIP_IBMCLOUD_SHOW=false        # nondefault
SPACESHIP_JOBS_SHOW=false            # true is default
SPACESHIP_JULIA_SHOW=false           # nondefault
SPACESHIP_KUBECTL_CONTEXT_SHOW=false # nondefault
SPACESHIP_PHP_SHOW=false             # nondefault
SPACESHIP_PYTHON_COLOR="green"       # nondefault
SPACESHIP_TIME_COLOR="white"
SPACESHIP_RUBY_COLOR="red"       # nondefault
SPACESHIP_RUBY_SHOW=true         # nondefault
SPACESHIP_RUST_SHOW=false        # nondefault
SPACESHIP_SWIFT_SHOW_LOCAL=false # nondefault
SPACESHIP_TIME_SHOW=true         # nondefault
# SPACESHIP_USER_SHOW="always"
SPACESHIP_VENV_SHOW=true         # nondefault
SPACESHIP_VI_MODE_SHOW=false     # nondefault
SPACESHIP_XCODE_SHOW_LOCAL=false # nondefault

# SPACESHIP_HG_SYMBOL: ☿
# SPACESHIP_ANSIBLE_SYMBOL: 🅐
# SPACESHIP_DOTNET_SYMBOL: .NET
# SPACESHIP_ASYNC_SYMBOL: …
# SPACESHIP_ELIXIR_SYMBOL: 💧
# SPACESHIP_IBMCLOUD_SYMBOL: 👔
# SPACESHIP_PULUMI_SYMBOL: 
# SPACESHIP_AWS_SYMBOL: ☁️
# SPACESHIP_ELM_SYMBOL: 🌳
# SPACESHIP_JAVA_SYMBOL: ☕
# SPACESHIP_PURESCRIPT_SYMBOL: ⇔
# SPACESHIP_AZURE_SYMBOL: ☁️
# SPACESHIP_ERLANG_SYMBOL: e
# SPACESHIP_PYTHON_SYMBOL: 🐍
# SPACESHIP_BATTERY_SYMBOL:
# SPACESHIP_JOBS_SYMBOL: ✦
# SPACESHIP_RUBY_SYMBOL: 💎
# SPACESHIP_JULIA_SYMBOL: ஃ
# SPACESHIP_EXIT_CODE_SYMBOL: ✘
# SPACESHIP_BUN_SYMBOL: 🍞
# SPACESHIP_RUST_SYMBOL: 🦀
# SPACESHIP_KOTLIN_SYMBOL: 🅺
# SPACESHIP_GCLOUD_SYMBOL: ☁️
# SPACESHIP_CHAR_SYMBOL: ➜
# SPACESHIP_SCALA_SYMBOL: 🆂
# SPACESHIP_SUDO_SYMBOL: ↯
# SPACESHIP_KUBECTL_SYMBOL: ☸️
# SPACESHIP_CONDA_SYMBOL: 🅒
# SPACESHIP_SWIFT_SYMBOL: 🐦
# SPACESHIP_CRYSTAL_SYMBOL: 🔮
# SPACESHIP_TERRAFORM_SYMBOL: 🛠
# SPACESHIP_LUA_SYMBOL: 🌙
# SPACESHIP_GIT_SYMBOL: 
# SPACESHIP_DART_SYMBOL: 🎯
# SPACESHIP_NIX_SHELL_SYMBOL: ❄
# SPACESHIP_GNU_SCREEN_SYMBOL: 💻
# SPACESHIP_DENO_SYMBOL: 🦕
# SPACESHIP_NODE_SYMBOL: ⬢
# SPACESHIP_DIR_LOCK_SYMBOL:  
# SPACESHIP_GOLANG_SYMBOL: 🐹
# SPACESHIP_VENV_SYMBOL:
# SPACESHIP_OCAML_SYMBOL: 🐫
# SPACESHIP_HASKELL_SYMBOL: λ
# SPACESHIP_VLANG_SYMBOL: V
# SPACESHIP_PACKAGE_SYMBOL: 📦
# SPACESHIP_DOCKER_COMPOSE_SYMBOL: 🐙
# SPACESHIP_XCODE_SYMBOL: 🛠
# SPACESHIP_PERL_SYMBOL: 🐪
# SPACESHIP_ZIG_SYMBOL: ⚡
# SPACESHIP_DOCKER_SYMBOL: 🐳
# SPACESHIP_PHP_SYMBOL: 🐘
